### ISSUE TITLE
Windows plugin fails to compile on VS 18.6

### ISSUE THREAD

**Issue by artdedeco** [MaikuB/flutter_local_notifications#2777]
**Describe the bug**
After updating Visual Studio to 18.6 (released on May 12), projects that depend on this package fail to compile on Windows. The update to 18.6 updates the MSVC toolchain to 14.51 which [now errors on usage of experimental coroutine headers](https://github.com/microsoft/STL/pull/5804).

> C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\include\experimental\coroutine(37,1): error C2338: static assertion failed: 'error STL1011: The /await compiler option, <experimental/coroutine>, <experimental/generator>, and <experimental/resumable> are deprecated by Microsoft and will be REMOVED SOON. They are superseded by the C++20 <coroutine> and C++23 <generator> headers. You can define _SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS to suppress this error for now.' [D:\source\MyTests\flutter_notifications_cpp20_bug\build\windows\x64\plugins\flutter_local_notifications_windows\shared\flutter_local_notifications_windows.vcxproj]

I'm guessing this is coming from one of the dependencies, or a transitive dependency; At least I couldn't find any /await switch or \<experimental\> headers on the windows plugin code.

Forcing CPP20 generates another error (perhaps revealing a bug):

> <redacted>\windows\flutter\ephemeral\.plugin_symlinks\flutter_local_notifications_windows\src\plugin.cpp(36,33): error C2440: 'initializing': cannot convert from 'ATL::CW2A' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' [<redacted>\build\windows\x64\plugins\flutter_local_notifications_windows\shared\flutter_local_notifications_windows.vcxproj]

**To Reproduce**
1. Install VS 18.6
2. flutter create --platforms windows cpp20bug
3. flutter pub add flutter_local_notifications
4. flutter build windows

**Expected behavior**
It builds

**Comment by Levi-Lesches** [comment]
To clarify, you said "Forcing CPP20" -- is that something you have to do manually? Or do new flutter templates do this now?

**Comment by artdedeco** [comment]
> To clarify, you said "Forcing CPP20" -- is that something you have to do manually? Or do new flutter templates do this now?

It's something I tried doing to work around the issue. You can choose both which language version to support and which toolchain version to use when compiling by passing flags to MSVC. In the case of flutter, you'd do that with CMake; I don't have the code with me right now, but it's basically setting the C++ 20 standard and v143 msvc flags in `windows/CMakeLists.txt`.

By the way, since then I have "fixed" the issue locally by compiling the plugin against C++ 20 and fixing the errors (that arise when using cpp20) mentioned in the OP. It's just two lines that are using an implicit conversion that is now an error instead of a warning. See [this issue](https://github.com/juliansteenbakker/flutter_secure_storage/issues/888) for an example on how to solve it (same pattern, same issue in another flutter plugin).

**Comment by dragonloverlord** [comment]
To make it compile I did the following and it worked fine enough.

In "flutter_local_notifications_windows/src/plugin.cpp"
Change this:

`const std::string key = CW2A(item.Key, CP_UTF8);`
`const std::string value = CW2A(item.Value, CP_UTF8);`

To this:
`const std::string key(CW2A(item.Key, CP_UTF8));`
`const std::string value(CW2A(item.Value, CP_UTF8));`

In "flutter_local_notifications_windows/src/CMakeLists.txt"
Change this:

`cmake_minimum_required(VERSION 3.10)`
`target_compile_features(flutter_local_notifications_windows PRIVATE cxx_std_17)`

To this:
`cmake_minimum_required(VERSION 3.12)`
`target_compile_features(flutter_local_notifications_windows PRIVATE cxx_std_20)`

Cmake minimum required is probably unnecessary but ver 3.12 is listed as the version CXX_STANDARD 20 was added in ([Source](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html)) So better to be safe I guess.

Edit: It didn't occur to me immediately but if you're trying to compile a project and having issues with the "error STL1011 /await compiler" thing then just add "_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS" to compile definitions.

AKA in YourFlutterApp\windows\CMakeLists.txt find:
`# Use Unicode for all projects.`
`add_definitions(-DUNICODE -D_UNICODE)`
And beneath this add:
`add_compile_definitions(_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)`

Second Edit: The previous definition location was wrong so fixed and sorry about that. Also adding this to your project does fix flutter_local_notifications compiling but it's likely only temporary as anything it silences will need to be changed to support the newer standards sooner or later as MS will undoubtedly stop allowing us to ignore the warning and this was probably the 'early warning bell' so to speak. Also worth noting that it's unlikely most devs will modify their CMakeLists.txt to work around this so best to assume defaults and make changes to support CXX_STANDARD 20 as that's likely to cause less friction overall as well as offer better future support / compatibility.

**Comment by MaikuB** [comment]
Thanks all for the info. I'll be getting a release out that suppresses the warning as per the PR in #2785. I have gone with this approach for now as a quick win as if I'm not mistaken and do correct me if I am mistaken, supporting CXX_STANDARD 20 would be considered a breaking change where this may force plugin consumers to update their build tooling. As version 22.0.0 of the plugin is quite new, I'm trying to avoid another major release
